### ISSUE TITLE
Lowercase 'o' similar to lowercase 'a'

### ISSUE THREAD

**Issue by paulrox** [googlefonts/great-vibes#10]
Hi,

The font is beautiful and really well done, however in my opinion the lowercase 'o' is too similar to the lowercase 'a' in the classical handwriting.

If you put the 'a' and the 'o' side-by-side you can see the difference but at first sight, the 'o' looks like an 'a'.

**Comment by vv-monsalve** [comment]
This change has been included as part of the upcoming update for the font.
