### ISSUE TITLE
GF-Plus addition

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#11]
- [x] Include the GF-Plus glyphset to the TSI Batch 1 projects.
- [x] Review the [previous issue](https://github.com/googlefonts/great-vibes/issues/10) opened by a user and provide him an answer

**Comment by RobLeuschke** [comment]
This font is ready for review.
GF Latin Plus is marked in pink. Some diacritics may need anchors (marked in red).

An alternate "o.ss01" has been created to address user's issue.

**Comment by RobLeuschke** [comment]
Great Vibes Update:
The GreatVibes file has been updated in the Dropbox folder. 
TypeSETit Fonts Batch1> GreatVibes> sources> GreatVibes-Pro. glyphs (this file is still in Glyphs version 2.67)

• The Cyrillic forms have been added to GreatVibes (marked with the color, dark grey). I recommend an expert consultant to check them and make sure there are no forms missing and that the font is operating well.
• The African Glyph set has been added but many forms are incomplete. I request help with how some of the characters and diacritic forms should be created (ie. acutemacron, gravemacron, macronacute and macrongrave). 
• Some of the hook forms may be incorrect. For example the hooks may have the wrong shape and may be 'traveling' in the wrong direction for some of these forms: Ɓ Ƈ Ɗ Ƒ Ɠ Ɦ Ƙ Ɲ Ƥ Ɋ Ƭ Ʈ Ʋ Ⱳ Ƴ ɓ ƈ ɗ ɠ ɦ ƙ ɲ ƥ ɋ ɾ ƭ ʈ ʋ ⱳ ƴ

**Comment by vv-monsalve** [comment]
Hi Rob, I'll download the new source file and provide feedback.

In the meantime, as we discussed in the meeting, when in doubt about any glyph you can:

- Check other fonts that also include the language. For African it could be [Questrial](https://fonts.google.com/specimen/Questrial?query=Questrial), [Merriweather](https://github.com/SorkinType/Merriweather/) and Eben mentioned Snell Roundhand. For Cyrillic you can filter the fonts in catalog by [Cyrilic](https://fonts.google.com/?subset=cyrillic&noto.script=Cyrl) as well as the [Google Fonts Discussions group](https://groups.google.com/g/googlefonts-discuss/c/9qV84-y1fqQ) that has some detailed feedback for previous projects. 
- Use the [Unicode Checker app](https://earthlingsoft.net/UnicodeChecker/) to easily inspect (by unicode) the other fonts supporting the language

**Comment by vv-monsalve** [comment]
Hi @RobLeuschke, after downloading the source file from DropBox (Jun 2023), I've made some changes and opened a couple of issues for the needed fixes. Please download the new Glyphs 3 file I've uploaded to DropBox (Jul 4 2023) before working on them.
- Numerals related fixes #13 
- Marks consistency fixes #14

To ease the process, I've bumped the version in the Source file to `1.011`. Please let's keep adding one digit before updating the file in DropBox. This would clearly show that we are working on the latest source file.

**Comment by vv-monsalve** [comment]
Closing this issue here as the pending issues are followed in separated issues.
