### ISSUE TITLE
Numerals fixes required

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#13]
Hi @RobLeuschke 

After inspecting at latest file uploaded to DropBox (Jun 2023) these would be the numerals fixes required (please use the source file I uploaded today -Jul 04 to DropBox):

### Superiors and inferiors

- [x] Please review the superior and inferior numbers' size, spacing, and position. 
You would like to read [Glyphs App tutorial about superscripts and subscripts](https://glyphsapp.com/learn/superscript-and-subscript-figures) for more details

**Superiors**
<img width="890" alt="Screen Shot 2023-07-04 at 16 21 22" src="https://github.com/googlefonts/great-vibes/assets/48698976/a21ecca7-d376-4022-a034-b3be2e96fd40">

**Inferiors**
<img width="890" alt="Screen Shot 2023-07-04 at 16 21 22" src="https://github.com/googlefonts/great-vibes/assets/48698976/06d08c90-c3c9-45bd-b6fb-ef96c221baba">

**Comment by vv-monsalve** [comment]
### Symbols that work with numerals

- [x] Please review the weight, size, and position of `degree`, `minute`, and `second`.
<img width="1274" alt="Screen Shot 2023-07-04 at 18 21 13" src="https://github.com/googlefonts/great-vibes/assets/48698976/ad882416-7d7c-45ca-87ee-88fecb3963ed">

**Comment by RobLeuschke** [comment]
The degree, minute and second glyphs are now more consistent with the design.

**Comment by RobLeuschke** [comment]
<img width="2025" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/5654ff86-9151-45d3-b1f9-e0b33d83d262">

I was reluctant to go smaller with the sizes, but did reduce them slightly by 5%.

**Comment by vv-monsalve** [comment]
> I was reluctant to go smaller with the sizes, but did reduce them slightly by 5%.

They look better, however you would like to review them in context, e.g. H₂O m³ Na₂ m²

**Comment by RobLeuschke** [comment]
I have decreased the sizes of the superior and inferior forms by 10% and adjusted the positioning of the superiors to accommodate the lowercase forms.

**Comment by RobLeuschke** [comment]
The inferior and superior numerals have been adjusted and are now kerned and spaced properly.

**Comment by vv-monsalve** [comment]
@RobLeuschke let's check this once again at the end of the Cyrillic work

**Comment by EbenSorkin** [comment]
Superior spacing seems good - made 3 adjustments to inferiors

**Comment by EbenSorkin** [comment]
It looks like we can close this.

**Comment by vv-monsalve** [comment]
I am closing this issue after the latest round of revision and fixes.
