### ISSUE TITLE
Marks consistency

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#14]
Please review the consistency among marks in terms of the following:

- [x] Style: stroke terminals, type of curves, and contrast. Especially among related shapes: `acute` - `grave` - `circumflex` - `caron`, where circumflex seems more coherent with the overall design of the font. 
- [x] Size + weight: `acute` and `grave` and `dotbelow` look big
- [x] Please review the above taking care of the used anchors, not deleting them plus keeping/adjusting (if needed) the position.

<img width="1833" alt="Screen Shot 2023-07-04 at 16 21 41" src="https://github.com/googlefonts/great-vibes/assets/48698976/0b72ead6-1a24-4bc0-abca-e6416f4d0185">

**Comment by RobLeuschke** [comment]
I have cleaned up some of the diacritic marks (grave, acute, ring, gravemacron, acutemacron, halfringleft, etc. and the dot accents). I believe they are now more consistent with the design of the font. I especially enlarged the ring accents. I thought they were too small and heavy. They are now more consistend with the half ring accents.

Please look at the placement of the Adotbelow and Aringbelow  glyghs. It appears to me that the dot is too far right. And, should the ring be touching the bottom of the A or should there be some distance. Unsure how to proceed.
<img width="572" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/ca344e70-f3ef-4604-bcfb-d702734d49c4">

**Comment by vv-monsalve** [comment]
> It appears to me that the dot is too far right.

I agree. It also looks a bit light or small, at least for the uppercase. Remember there could be a `.case` version of the marks and adjust them for the capital letters.

> should the ring be touching the bottom of the A or should there be some distance.

There should be some distance. This new ring looks a bit big or heavy. You would like to make it smaller and with a bit more contrast to better match the font contrast.

**Comment by RobLeuschke** [comment]
I have adjusted ring forms as well as the bottom anchors of the base A. This has helped the distance issue with the ring below. I'm not sure what glyphs will be effected if I play with the size of the .case forms.

**Comment by vv-monsalve** [comment]
> I'm not sure what glyphs will be effected if I play with the size of the .case forms.

Remember that once opening the glyph (mark in this case), you could right-click and pick "Show all glyphs that use this glyph as a component" to see which are affected.

**Comment by vv-monsalve** [comment]
@RobLeuschke diagonal marks look more consistent now. However, `breve` and `hookabove` look out of the system (in the type of curves and stroke endings). Some of them are shifted now.
<img width="2211" alt="Screen Shot 2023-08-14 at 20 07 51" src="https://github.com/googlefonts/great-vibes/assets/48698976/c629f0e6-3625-489f-9177-40c9959a1972">

Please take a look at the width of the diagonal marks, and `macron`. They are going too close to adjacent letters.

<img width="1047" alt="Screen Shot 2023-08-14 at 19 18 00" src="https://github.com/googlefonts/great-vibes/assets/48698976/501bbd8c-84a6-4973-951e-fb416d404bbb">

**Comment by EbenSorkin** [comment]
The hook above in the second word upper right is part of  compound diacritic and the hook above should be raised and then moved in close to the circumflex. This is how I did it in Merriweather
<img width="717" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/b578b821-3fc0-422a-a8b1-34cddbdfd5f1">

**Comment by RobLeuschke** [comment]
Here are my revisions. 
I did modify slightly the hookabove, carons, macrons and graves.
I gave lcaron a wider connecting stroke to give more room for the diacritic and characters following. 
I also decomposed the circumflexcomb_gravecomb, and made the circumflex slightly lighter in weight (it looked heavy with the grave). 

<img width="1077" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/07352018-e24b-4cb8-886b-3dbe316d99b2">

**Comment by EbenSorkin** [comment]
This looks good but the Caron should be pages down slightly and the
circumflex just a bit deeper even because it seems to float higher when it
is placed at an mathematically identical height to Caron

**Comment by RobLeuschke** [comment]
The diacritics have been modified.

**Comment by vv-monsalve** [comment]
I've performed an overall revision and fixes to the Latin Core marks in the latest file in the repo (at commit `8785c7b33b9`). 
@EbenSorkin I've marked red or orange the ones that are part of SSA. Please review them and provide feedback

**Comment by EbenSorkin** [comment]
Ok I have cloned the repo. I'll start looking now.

**Comment by vv-monsalve** [comment]
After the latest revision to Latin marks, they are looking better now. 
@RobLeuschke please take all the changes in consideration in case you need to create any new one for the added languages.
