### ISSUE TITLE
Approach to the Hook issue

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/great-vibes#15]
<img width="464" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/0f6d2179-f733-4102-aebf-e618d367b757">

It may be that the ideal way to have a hook in this style is to add it to a main form but I suspect that instead it meant to be integral to the form like the tail of the j.

**Comment by EbenSorkin** [comment]
Denis (@moyogo, an African Latin expert) says the `g` `c` with hook is OK.  `Y` `y` `v` `w` `b` `d` `h` `k` `n` `p` `q`  all need to have hooks that extend from a stem and are part of the stem. with t hook above a different form of t without a loop would be preferable.

**Comment by RobLeuschke** [comment]
I've been working on the hooked forms. The lowercase are getting better... and I need a constructive critique to be sure I am moving in the right direction...
I've made these with the original forms first, plus an "r" to show how they connect, and then the hooked form:
<img width="1009" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/946d8589-b81b-4b34-af91-3215bd4298c9">

The caps are more problematic and I have created several alternate options for a few of them, that we may discuss:
<img width="1273" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/44efb5d3-0476-48c8-9f09-f517f9ad48b0">

**Comment by EbenSorkin** [comment]
These seem successful overall. I think the ascending hooks may be more
expected coming to height more similar to the base letters. E.g. d and
dhook having more matching ascending heights. I am cc’ing Denis to see what
his intuition is.

In the case of t hooks if the hook was less wide that would be better. Lc p
hook and b hook could also be slightly less wide. If the g and c hooks were
better integrated and emerged from strokes and were just a bit heavier they
would seem less diacritic like and more a part of the letter itself.

I the caps one thing we discussed but maybe just didn’t look good when you
tried it was the idea of the hook arcing halfway and ending. The W hook and
Vhook do this but the T D P do not. I’m still curious about the idea of the
truncated gesture letting us signal difference from the more opulent
flourish.

**Comment by moyogo** [comment]
Most lowercase look good now.

Considering j has a loop, ɲ could have a loop as well.
<img width="419" alt="Screenshot 2023-07-08 at 07 58 46" src="https://github.com/googlefonts/great-vibes/assets/1923747/d6acc670-ca27-4e15-8b77-82592571a0c8">

Often the hooks can be loops in this kind of hand styles, there’s a few context where the distinction needs to be maintained. In this case Ʝʝ are historically j with loop but in this hand style the loop can end pointing downwards for ʝ in particular.
Looking at your new ɓɗɦƙƥƭ they look good, I wouldn’t use the loop for those in this style.
Do you have ƒʃ already?

The current default t is going to clash with ƚ, so an alternate t similar to t.ss01 but with a straight bar would be needed for the orthographies using ƚ.
I agree the hook of ƭ could be smaller but it might actually work with more context.

For the retroflex hooks, they could be loops as well like the bottom of f.
For ɽ the retroflex hook can be on the right stem of the letter, it would flow better (as the current retroflex hook or as a f-like hook).

I think ⱳƴ look good but I might come back to it.

For the uppercase, it’s not clear what’s the best approach.
- There can be an analogy with I and J, where the J is an I with a more pronounced hook. In that case the hooked capital letters would have more salient hooks but it’s difficult in this hand style.
- The hooks can be loops.
- The hooks can be drop terminals. Historically the ƁƊƘꞪƳⱲ replaced letters with apostrophe, and ɖⱤƮ replaced letters with dot below, there is some traced of ligation in some cases. So drop terminals or dark small loops could work as well.

I like the last Ƭ (before Tretroflexhook) and the last Ƥ.
Tretroflexhook Ʈ should have its hook to the right, not to the left.
For ƘƳⱲ, the hooks can be larger.

For what it’s worth the [1930 *The New Script*](https://archive.org/details/the-new-script-and-its-relation-with-the-languages-of-the-gold-coast/page/8/mode/1up) has some cursive forms, but it only has Ɖɖ and it seems dated.

**Comment by RobLeuschke** [comment]
This is very helpful. Thanks. 
I do have quite a few questions for some of the forms. For example, what is the difference between the 'eturned' and the 'schwa'?

Hopefully some of these can be answered tomorrow— assuming we are still planning to meet.

**Comment by EbenSorkin** [comment]
What time would suit you today? 10 EST?

**Comment by EbenSorkin** [comment]
The e turned and schwa in lower case look identical. They just have
different Unicodes. You can make e turned use the schwa as a component. An
e component can be used to make schwa too at first but it will probably
need its own spacing and the e component making the schwa will need to be
decomposed.

**Comment by RobLeuschke** [comment]
I thought that may be the situation, but didn't want to make any assumptions.

**Comment by RobLeuschke** [comment]
I'm sorry about not meeting today. Morning is problematic for me, while afternoons is much better for me. Perhaps we can make it tomorrow or Thursday? I can go as early as 11:00 AM (central time). 

In the meantime, I've been modifying some of the hooked forms:
<img width="946" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/5918fcb8-e231-45ad-b56b-da5f3d3123c2">

**Comment by RobLeuschke** [comment]
I have completed the African Character set that was provided to me, but I am sure there are likely issues with some of the forms that will need to be addressed. Please advise when we may next meet to review and discuss.

Also, there may be a few Cyrillic characters that need to be created, and I will need some expert help with them as well.

**Comment by RobLeuschke** [comment]
After doing a little bit of study of the wonderful resource of the "New Script" pdf, I think I may have the "Ƞ" incorrect, so I have made an alternate that I think may be more reflective of how it should be rendered. The bottom one here is the original and the top, with the loop is new.

<img width="785" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/0def3715-3617-49ac-87db-6c64e667fbe6">

**Comment by EbenSorkin** [comment]
What is the URL for that PDF?

Do your Capitals join with lower case some of the time?

-e.

**Comment by RobLeuschke** [comment]
Yes, some (but not all) of the capitals connect to lower case forms. 
Here is the link to the New Script resource:
https://archive.org/details/the-new-script-and-its-relation-with-the-languages-of-the-gold-coast/page/21/mode/1up

**Comment by RobLeuschke** [comment]
Based on our meeting today, I've made some modifications to the lowercase. I also created two additional rfishhooks and I think I like the second one shown here best. 
<img width="1540" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/617e3923-b2ea-4bda-b0c6-db8a9dda98cb">

**Comment by RobLeuschke** [comment]
I have revised the stroked forms for the African language, and created a better Lambdastroke form that connects.
<img width="1024" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/e56b0cef-50c6-4d98-81e8-1cdd6fd3f18d">

There is also now a F.ss02 to accommodate the Vietnamese diacritic forms. I'll need help with programming these contextual combinations.

**Comment by RobLeuschke** [comment]
I've either deleted the former hooked forms (or renamed them) and replaced them with these latest forms. The Qhooktail is now more consistent with the Tretroflexhook.
<img width="1137" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/2260a3df-f3e1-40d4-a47d-ce5209ed6d06">

**Comment by RobLeuschke** [comment]
Just like the alternate F, there is now an alternate T (.ss02) that has been created to accommodate the diacritics that may crash with the base T.
<img width="1548" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/b9148dd8-1068-4e64-8cc6-d660f2e68694">

**Comment by RobLeuschke** [comment]
I've made revisions to the Eng and nhook forms. 
Please advise on other issues that I can work on.

<img width="517" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/98ab1809-fd46-4108-a01c-3727c075aa16">

**Comment by EbenSorkin** [comment]
Rob, will you email me a copy of the file so I can put it through some
paces and see what I recommend doing next? I suspect it will be slashed and
barred letters and some diacritics next.

Vivi we discussed naming strategies to prevent over writing anything.

**Comment by RobLeuschke** [comment]
Hi everyone,

Eben,
 I just sent the file to you. If you recall, there are likely some
programming needs with regard to the alternate F and T forms that were
created to address crashing issues with some of the diacritics.

Rob

**Comment by vv-monsalve** [comment]
These are the current lowercase hooked letters and upper and lowercase letters with strokes in the font.
@EbenSorkin, please check them out, and if you find them ok now, please feel free to close this issue.

Rob, please review the weight or "bumps" discussed in the meeting.
 
<img width="1522" alt="Screen Shot 2023-08-14 at 19 51 13" src="https://github.com/googlefonts/great-vibes/assets/48698976/ed3078d5-a0f1-48ac-a39e-23089f2b6595">

<img width="1276" alt="Screen Shot 2023-08-14 at 20 00 14" src="https://github.com/googlefonts/great-vibes/assets/48698976/96ff243e-3bc5-4ca9-b45e-7e1dd122025c">

**Comment by EbenSorkin** [comment]
I'd like to see the bars made thinner ( like in pbar ) so that they are similar in thickness with the crossbar in t. This will help keep a more even color in letters that are otherwise going to trend too dark even in ideal conditions and we do everything right. the diagonal slashes look very good. The bar is the cap forms is also too think but even more so.

**Comment by RobLeuschke** [comment]
I'll be working on these next. In the meantime, I revised the J crossedtail ... it looked to heavy to me:
Before:
![image](https://github.com/googlefonts/great-vibes/assets/57553693/009f8647-22dc-424c-88e7-88a861b014a2)
After:
![image](https://github.com/googlefonts/great-vibes/assets/57553693/66280283-725c-4ff0-8242-b9bf94e2db54)

**Comment by RobLeuschke** [comment]
I've revised the Jcrossedtail. It looked a bit heavy and clunky to me.
BEFORE:
![image](https://github.com/googlefonts/great-vibes/assets/57553693/1dc3f953-c59a-4607-bd8a-798d73b99901)


REVISED:
<img width="626" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/33b10119-152b-432b-8ff0-b3442fa1ef52">

**Comment by EbenSorkin** [comment]
Something went wrong with the after image. I need to go see if I think the
solutions for the  G and g with bar seem to be the best.

**Comment by EbenSorkin** [comment]
The rfishhook ss01 seems like the one to be default.

**Comment by RobLeuschke** [comment]
I've adjusted the stroked characters... mostly the lc, but there were a couple of uc characters I tended to as well:
<img width="1157" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/f82fab96-cc2f-4f59-9599-80b2e7ac10e0">

**Comment by EbenSorkin** [comment]
Reading this

https://en.m.wikipedia.org/wiki/G_with_stroke

It sounds like Denis and I may have missed a localization. I better ask him.

**Comment by RobLeuschke** [comment]
Are these better? If not, I think I need some help:
<img width="1324" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/b81b71ae-87f8-4fa7-b17e-39a4710a9896">

**Comment by EbenSorkin** [comment]
Yes but I think I need to resolve a question or two with Denis to be sure
re: the G question.

**Comment by EbenSorkin** [comment]
I have asked him for advice now.

**Comment by moyogo** [comment]
The hook letters:
- /rfishhook.ss01 would be the only form recognizable as an rfishhook... it doesn’t have a hook below like the current rfishhook and isn’ an r with a hook on top like rfishhook.ss02. But the character is not used in SSA orthographies or other orthographies anyway. I’d recommend removing it completely as it is only an IPA phonetic symbol.
- /Vhook/vhook should have their right hook pointing left on the inside of the letter, meaning instead of pointing right. In this design it might make more sense to have an extra hook on the left stroke, separate from the joing stroke which can remain. In Antiqua and Grotesk, it usually has the shape of a round v with one right pointing left inside or that Greek υ with an extra left hook. The second with an extra hook would help differentiating it from v here. In Loma in Liberia it typically has the shape of an angular v with a high right hook pointing left inside. In this design that Loma variant would just have a high hook.
<img width="1039" alt="Screenshot 2023-08-16 at 22 30 54" src="https://github.com/googlefonts/great-vibes/assets/1923747/1d724fe9-66e1-4eb0-aa9a-e8e961d0b060">

The crossed tail letters:
- /Jcrossedtail can have its loop crossed tail terminating pointing down
<img width="320" alt="Screenshot 2023-08-16 at 22 20 55" src="https://github.com/googlefonts/great-vibes/assets/1923747/6962e391-02dc-4869-a3c4-79c0686ab62e">

The stroke letters
- /Bstroke is good now with the stroke through the letter, like /Eth on the left part of the letter
- /gstroke is typically with a stroke through the descender, only a few fonts have the stroke through the bowl of the letter. Having it through the descender loop would be more consistent.
  For the G with median stroke (through bowl of lowercase and left of bowl of uppercase) use in Kadiweu or a few other places, a variant with a median stroke in both the uppercase (new) and lowercase (current) could be added but there isn’t any Kadiweu OpenType Language System tag yet
- /Gstroke usually has the stroke through the right part of the bowl, in this design your updated /Gstroke looks fine.
- I think /Rstroke should have the stroke through the whole letter instead of just on the left in this design.
- /Sobliquestroke/sobliquestroke can be removed. The S with diagonal stroke (through the whole letter), used in orthographies, is not a variant as specific Unicode characters will be in Unicode 16.0 next year.

**Comment by RobLeuschke** [comment]
"I’d recommend removing it completely as it is only an IPA phonetic symbol."

              @moyogo —     Are you saying it isn't really used, and  I should just remove all rfishhooks completely? And the same with the /Sobliquestroke/sobliquestroke?
______________________________
Based on Deni's comments I have made alternate Vhook glyphs that we can discuss. I'm wondering if I understood your comments correctly (@moyogo 
<img width="592" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/e2a22d8a-a059-46d5-aae4-d2eb24cc6025">

Regarding the gstroke, is this more what you have in mind:
<img width="697" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/def4787d-3c30-4cb8-9034-04d876a57286">

Rstroke: More like this?:
<img width="1270" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/3bfcd2ef-9d96-45bd-a37b-41a3a0712811">


The Jcrossedtail has been revised:
<img width="652" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/a02bfdde-ba94-4650-8851-af6fe926c580">

**Comment by moyogo** [comment]
>> "I’d recommend removing it completely as it is only an IPA phonetic symbol."
> 
>  @moyogo —     Are you saying it isn't really used, and  I should just remove all rfishhooks completely? And the same with the /Sobliquestroke/sobliquestroke?


Yes, I’d recommend removing /rfishhook/Sobliquestroke/sobliquestroke glyphs. /rfishhook isn’t necessary for any orthographies and /Sobliquestroke/sobliquestroke are the wrong characters for S with diagonal stroke. (S with oblique stroke is not adequate, Unicode 16.0 will have the adequate S with diagonal stroke characters)


> Based on Deni's comments I have made alternate Vhook glyphs that we can discuss. I'm wondering if I understood your comments correctly

That look good! The hook can be simplified for this letter and have the stroke go directly into the hook without the additional knot. Maybe the uppercase could also have a slightly raised hook like the lowercase, that would help distinguishing it from the V. Having a distinct starting terminal definitely helps; a similar approach may be needed for /iota-latin to distinguish it from /idotless).
<img width="366" alt="Screenshot 2023-08-18 at 22 16 46" src="https://github.com/googlefonts/great-vibes/assets/1923747/a0f9b88a-3255-43ba-9369-5a9da80ed0b3">

> Regarding the gstroke, is this more what you have in mind:
<img alt="image" width="348" src="https://user-images.githubusercontent.com/57553693/261446467-def4787d-3c30-4cb8-9034-04d876a57286.png">

The new one looks good. The stroke can also cross the whole descender loop.

> Rstroke: More like this?:
<img alt="image" width="363" src="https://user-images.githubusercontent.com/57553693/261447004-3bfcd2ef-9d96-45bd-a37b-41a3a0712811.png">

Yes. I don’t think this hand style needs to stick to the stricly on-the-left stroke (even grotesque or antiqua style don’t have to). Alternatively, the stroke could be on the top or on the bottom of the left stem. The one with the lowered stroke through the whole letter seems to be the most natural when handwriting it.
<img width="587" alt="Screenshot 2023-08-18 at 22 25 27" src="https://github.com/googlefonts/great-vibes/assets/1923747/62dfecec-1af1-4d5f-a51f-e843f1e19def">


> The Jcrossedtail has been revised: <img alt="image" width="652" src="https://user-images.githubusercontent.com/57553693/261433043-a02bfdde-ba94-4650-8851-af6fe926c580.png">

Great!

**Comment by moyogo** [comment]
For Fhook, the left hook should be on the bottom.
In this case, the hook can also be simplified and there can be a symmerty between the pair F and Ƒ (F with hook) and the pair I and J (I with hook).
<img width="431" alt="Screenshot 2023-08-18 at 22 37 11" src="https://github.com/googlefonts/great-vibes/assets/1923747/b53f036c-59f7-404b-8401-358ac37bce56">

**Comment by vv-monsalve** [comment]
@EbenSorkin I've pushed now a new [source file](https://github.com/googlefonts/great-vibes/blob/QA-GreatV/sources/GreatVibes-Pro.glyphs) to the QA-GreatV branch -commit `8785c7b` (this is the same file I've just uploaded to DropBox @RobLeuschke)


Could you please inspect all the above has been solved?

**Comment by EbenSorkin** [comment]
It looks like it has - yes.

**Comment by EbenSorkin** [comment]
I will look tonight. Yes.

**Comment by vv-monsalve** [comment]
We agreed with Rob that he'll make a final round to tighten up the outlines and check for the node's quantity and position, making the curves smooth at the end of the process.

**Comment by EbenSorkin** [comment]
Sounds good!
