### ISSUE TITLE
Capital hooks

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/great-vibes#16]
<img width="795" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/a88f543b-5758-4f03-986c-265b6f21084f">

Please cross-check with Denis: but 

The Nhook the sense I have is that the hook is mean to be an abbreviated version of the capital `J` or lc `j` shape

<img width="123" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/939b11e1-7731-49f8-a578-6b57ff014f39">

With `Ghook` the hook does seem to be added but the scale and presence needs to be greater so that the fact that the hook is there and is the key to the letter identity is made less muted.

With `Hhook` and `Dhook` we are really dealing with quite a hard design issue here because the *existing* flourish is near and indeed exceeds the scale that is expected for hook for this letter. I think probably there are two paths here: 1) make the hook smaller and flatter so that a visual distinction from the base letter `D` is easy to observe and you avoid having two hook-like shapes. 2) permit two hook-like shapes but make the 'new' hook emerge from the stem of `D` not the flourish.

With `Khook` the upper right stoke should become the hook itself rather than having a one attached.

**Comment by vv-monsalve** [comment]
These are the latest hooked letters in the font. @EbenSorkin, please give them a look, and if you find them ok, feel free to close this issue

@RobLeuschke, Please remember to review the weight and "bumps" we discussed today at the meeting.
<img width="1609" alt="Screen Shot 2023-08-14 at 19 36 10" src="https://github.com/googlefonts/great-vibes/assets/48698976/35bc3f62-a8bb-4832-bd1e-10ae653e49a0">

<img width="1609" alt="Screen Shot 2023-08-14 at 19 42 03" src="https://github.com/googlefonts/great-vibes/assets/48698976/a1217d3c-5caa-4e7e-a7de-6d2c8a80294e">
