### ISSUE TITLE
Vietnamese diacritics

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/great-vibes#17]
<img width="367" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/4d1bee27-0f71-46ca-8e98-3e9072eb760b">

Mostly these look fairly reasonable on their own but there are some reasons to decompose them and adjust them:

• if they are decomposed and scaled down slightly that tracks with expected best practices for this language 
•  If they are a decomosed, then you can let the lower shape be a bit bigger than the top one which is also best practice and also that gives a more pleasant sens eof visual hierarchy to the diacritic mark
• The overall smaller combined diacritic can be made to clash with fewer capital letters that might come before the lower case letter.

**Comment by RobLeuschke** [comment]
I've addressed this issue and corrected situations of crashing by using both kerning and slightly adjusting the sizes and positions of the combination diacritics.

**Comment by crystaltype** [comment]
Fyi: we don’t use most of those pairings in Vietnamese (maybe Tằng Tắng -
rarely used; and Tăng - frequently used). I’d recommend checking out Tốt /
Tết / Tất / Tắt / Tít in script typefaces as they’re used pretty often in
Vietnamese.

**Comment by vv-monsalve** [comment]
Thanks, @crystaltype, for the feedback.
Following it and what we discussed today in the meeting, we should at least address the known common combinations. It could be another case for the `calt` feature.

<img width="1385" alt="Screen Shot 2023-08-14 at 19 29 34" src="https://github.com/googlefonts/great-vibes/assets/48698976/166c9987-9e1f-4104-b416-571430cc8b11">

**Comment by EbenSorkin** [comment]
The first three might be addressed by scaling the diacritics down in size and placing them closer to the lowercase letter. The circumfex shape is riding a little high. The relative scale of the circumflex with the acute is good. The Breve+Acute is placed nicely but the acute part could be lowered. for potentially more clarity. In the second to last example, the breve with the grave  - the grave could again be made to fit close to the breve. I think these changes would be much easier than making an alt T.

**Comment by vv-monsalve** [comment]
Solved in version v1.016

<img width="712" alt="Screen Shot 2023-10-09 at 16 19 26" src="https://github.com/googlefonts/great-vibes/assets/48698976/5c7339e1-097b-4880-9c33-935a51c3a661">
