### ISSUE TITLE
Algonquin OU 

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/great-vibes#18]
<img width="1003" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/4981d914-c4de-47a1-a159-1d4ed92c4648">

I think the OU should perhaps be a little wider. Happily, the height of it establishes it as a capital letter to some degree but the lack of swashes and modest width combine to make it less clear than it might otherwise be.

<img width="683" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/0eb3aa61-c889-4b61-8521-f5ec3a4ca72e">

**Comment by moyogo** [comment]
Note: OU is used in some orthographies of Algonquin languages in North America, not in Africa.

**Comment by RobLeuschke** [comment]
I have adjusted the width of the OU.
<img width="857" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/3333f5d8-6a42-4afd-b2ad-e48b5c4e858f">

**Comment by EbenSorkin** [comment]
I like it! I think the width could be more still but Let's see what Denis
says.

**Comment by vv-monsalve** [comment]
Current `OU` in the font. @EbenSorkin, please give it a look and if you find it ok now, please close the issue.

<img width="648" alt="Screen Shot 2023-08-14 at 19 26 08" src="https://github.com/googlefonts/great-vibes/assets/48698976/16f2268c-cdc6-4b2e-92f5-bb61570cbb59">

**Comment by EbenSorkin** [comment]
The capital OU seems good but the lowercase one feels a bit too wide. More with the o than the u, but ultimately both are wider than I think will probably be ideal.

**Comment by RobLeuschke** [comment]
Better?
<img width="967" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/5b0b7cc4-5754-49e7-880e-5024ee6dfb04">

**Comment by EbenSorkin** [comment]
Yes. But I think it is still too wide compared to the o.

**Comment by RobLeuschke** [comment]
<img width="950" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/dda6005a-2cf3-4b14-9d01-36c0c309281e">
Perhaps this is better?

**Comment by moyogo** [comment]
>  Perhaps this is better? 

I think this width works for the lowercase.

Just one note, the stroke would go from the top left into the bottom loop, and back up to the top right.
<img width="154" alt="Screenshot 2023-08-18 at 21 53 01" src="https://github.com/googlefonts/great-vibes/assets/1923747/ffd23a5f-5fc1-4f06-81eb-54c1c69f2494">

Just for some background, the letter ou comes from the Greek ου ligature and is usually replaced by the digit 8 in modern text. It used to often be short, at x-height, but when it was added to Unicode the representative glyph is tall like the digit 8.

Overall, a shape like the 8 but open on top may better reflect the identity of the letter. The capital would be wider to avoid confusion but the top part should have the same width as the bottom part, like you have in your lowercase;

**Comment by RobLeuschke** [comment]
The base "ou" has been modified, and I created a stylistic version (ss01) with a more "8" shape.
Please advise as to which (or both) is more appropriate. I personally prefer the first.
<img width="385" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/73c70d3e-5246-4c98-89f5-610809dbfd02">

**Comment by moyogo** [comment]
@RobLeuschke both work, go for the first if that makes more sense with your design.

Looking at some manuscripts, the pen can do both, a slower one with two shapes on top of each other and a faster one in a single go:
<img width="533" alt="Screenshot 2023-10-02 at 16 21 08" src="https://github.com/googlefonts/great-vibes/assets/1923747/22865f26-9c7f-4bce-89bf-2f686be2df75">

The faster one can also have a different exit-stroke.
<img width="145" alt="Screenshot 2023-10-02 at 16 23 06" src="https://github.com/googlefonts/great-vibes/assets/1923747/af4c8b2e-9b0d-42ce-a84e-b11b25a3c93e">

**Comment by vv-monsalve** [comment]
The second version was kept as .ss01
