### ISSUE TITLE
Stylistic Sets

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#19]
Please review all the Stylistic Sets and ensure the following:

- [x] Check the style (e.g. `o.ss01`) and spacing and connections are ok e.g. `g.ss02` `lm` 
- [x] Asigning a descriptive name for each feature. You can check the [Glyphs App Stylistic Sets tutorial](https://glyphsapp.com/learn/stylistic-sets)
- [x] Review the `ss03` (that only consist of `z`s) Vs. the main version and choose only one and then adjust the weight. Both versions look heavy for the font.

<img width="1598" alt="Screen Shot 2023-07-06 at 13 29 32" src="https://github.com/googlefonts/great-vibes/assets/48698976/f76fb20e-c9b5-4108-b5f1-55a61c90c392">
<img width="1598" alt="Screen Shot 2023-07-06 at 13 28 57" src="https://github.com/googlefonts/great-vibes/assets/48698976/e34d8133-2cb5-402d-a1bb-c43bb442a419">
<img width="1598" alt="Screen Shot 2023-07-06 at 13 28 35" src="https://github.com/googlefonts/great-vibes/assets/48698976/06afb807-d587-4575-a757-669c3b20092b">

<img width="992" alt="Screen Shot 2023-07-06 at 13 13 30" src="https://github.com/googlefonts/great-vibes/assets/48698976/12eaeda1-5a43-4190-9c03-2324b9fd9eb0">

**Comment by RobLeuschke** [comment]
I have made adjustments to weights and taken a look at the spacing. I added missing diacritics to the z stylistic versions (z.ss01-3).

Spacing for some of the character combinations can be problematic (crashing of descenders on the g, for example). These issues will need to be addressed by the end user as there are alternates that can be substituted to avoid such crashing.

**Comment by vv-monsalve** [comment]
The stylistic sets still need to be named. `ss03` currently has a `Name:` name. In that field is where the actual name should go.

<img width="746" alt="Screen Shot 2023-08-14 at 19 07 06" src="https://github.com/googlefonts/great-vibes/assets/48698976/43eb4aeb-4464-4dc1-9d08-b4e065b5beba">

**Comment by vv-monsalve** [comment]
In `ss01`, the `t` bar could go a little down for it to better follow the position game with accents.
Also, please review all the connections.

<img width="1081" alt="Screen Shot 2023-08-14 at 19 08 23" src="https://github.com/googlefonts/great-vibes/assets/48698976/b81a70bd-9c93-46ce-9dc7-cfd997d34237">

**Comment by vv-monsalve** [comment]
In `ss02`, please review the size of `d` loop. It looks a bit big and is colliding with other letters.

<img width="568" alt="Screen Shot 2023-08-14 at 19 48 04" src="https://github.com/googlefonts/great-vibes/assets/48698976/fe088847-db8e-440a-9f69-b914c0109bbe">

**Comment by RobLeuschke** [comment]
<img width="913" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/733f1d84-6d2a-4b0f-ae05-1086b64784b0">

I have given the singlequote and doublequote a skew to be more consistent with the design of the font. 

The crossbar on the t.ss01 has been adjusted.

The r.ss01, and r.ss02 are actually designed to be initial forms. I am reluctant to change the suffix to .init because the font is being used by the public and it could cause issues for them. 

And I have adjusted the d.ss02.

**Comment by vv-monsalve** [comment]
> The r.ss01, and r.ss02 are actually designed to be initial forms. I am reluctant to change the suffix to .init because the font is being used by the public and it could cause issues for them.

@davelab6 What would you say?

**Comment by RobLeuschke** [comment]
I have created a "t.alt" form that I wish could be the base. (I don't like the looped "t" that is the base form).
Would it be ok to have this new "t" as the CALT form? If not, I suppose it could simply be in a stylistic set.
<img width="816" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/a67dc824-5f7e-457e-bff7-684c99b081f9">

**Comment by vv-monsalve** [comment]
I like this simplified `t`, I think it could be the base form and keep the other as a .ss01. 
What would you say @EbenSorkin?

**Comment by RobLeuschke** [comment]
I have swapped out the t's so that the more simplified is the base glyph. The original "t" is now t.ss01.
<img width="380" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/15bfa339-d648-4c74-b139-e3a34854970e">

**Comment by vv-monsalve** [comment]
This is working now in v1.016
