### ISSUE TITLE
Outlines

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#20]
Please review the skew, weight, and contrast distribution of the following letters

### `b`

Lowercase b looks wider and lighter than the others and differs significantly from their "group" companions `d`, `p`, `q`, which affects the weight balance in the letters

<img width="1522" alt="Screen Shot 2023-08-14 at 19 55 29" src="https://github.com/googlefonts/great-vibes/assets/48698976/dc94435d-e38f-45c4-8b68-737db1a8d95c">

**Comment by vv-monsalve** [comment]
### Open letters

Similar to what happens in `b`, please review `oopen` and `eopen` (bot lowercase and Uppercase) to ensure the skew, width, weight, and contrast are consistent with the whole font.
Please review the connections too.

<img width="1423" alt="Screen Shot 2023-08-14 at 20 23 39" src="https://github.com/googlefonts/great-vibes/assets/48698976/3f91dcb1-2747-415c-b0d1-9637dea6d6be">
<img width="749" alt="Screen Shot 2023-08-14 at 20 22 31" src="https://github.com/googlefonts/great-vibes/assets/48698976/65a4931a-e6b2-4edc-b5fd-6e6fc4cf0369">
<img width="749" alt="Screen Shot 2023-08-14 at 20 22 42" src="https://github.com/googlefonts/great-vibes/assets/48698976/d8c94746-767a-432e-ac9b-7e3bb19d244f">

**Comment by vv-monsalve** [comment]
### `quotesingle`

It must be consistent with the font slant, also please review the spacing.


<img width="1081" alt="Screen Shot 2023-08-14 at 19 05 33" src="https://github.com/googlefonts/great-vibes/assets/48698976/3adaa540-b5c8-451e-b3b6-42ec7e685341">

**Comment by RobLeuschke** [comment]
Yes, the 'b' was way too wide. I have revised it, and made the imacron  work a bit better:
<img width="1234" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/0cb0ced0-ac35-4e5f-aad8-1dba4d1ee7e0">

I've also reduced the size of the 'eopen' and made it so it connects. Please let me know if this is an appropriate way to handle this letter. Thanks.
<img width="719" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/55f467cf-9240-40d3-8032-bc1e8fcf4f13">

**Comment by vv-monsalve** [comment]
I'm adding some pictures here, following what we discussed during the meeting today so that you solve similar issues while working on the glyphs.

<img width="500" alt="Screen Shot 2023-09-28 at 21 49 29" src="https://github.com/googlefonts/great-vibes/assets/48698976/3ba639f9-8e85-4435-96fd-f967063ca08b">
<img width="500" alt="Screen Shot 2023-09-28 at 21 49 36" src="https://github.com/googlefonts/great-vibes/assets/48698976/3ebbe14b-7879-4f92-b803-2394935b107e">
<img width="250" alt="Screen Shot 2023-09-28 at 21 32 54" src="https://github.com/googlefonts/great-vibes/assets/48698976/d88901ba-17c9-49a8-b63b-a2386d0c949a">
<img width="500" alt="Screen Shot 2023-09-28 at 21 34 45" src="https://github.com/googlefonts/great-vibes/assets/48698976/d7d2ef69-bb0b-4107-b594-bf6d1370a386">

Thickness and contrast 
<img width="500" alt="Screen Shot 2023-09-28 at 19 51 51" src="https://github.com/googlefonts/great-vibes/assets/48698976/347d4d4c-741b-48c0-8ed3-0844c0f86b6f">
<img width="500" alt="Screen Shot 2023-09-28 at 19 52 01" src="https://github.com/googlefonts/great-vibes/assets/48698976/14ddf886-50b7-4421-b2db-322a90ccbefe">

**Comment by RobLeuschke** [comment]
the glyphs of the following letters have been modified for better connections:
<img width="1308" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/ab9d1207-6e9e-4a16-97ad-b468a7b8351a">

**Comment by RobLeuschke** [comment]
I've also addressed the thickness and contrast issues mentioned.

**Comment by vv-monsalve** [comment]
Rob is going to review the connector on the `o` and the initial stroke in `oopen` for the connection to work more smoothly

**Comment by RobLeuschke** [comment]
@vv-monsalve 
I think all of the issues listed here have been addressed. Feel free to close these issues.

**Comment by EbenSorkin** [comment]
Adjusted spacing of quotes 
<img width="650" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/d292f252-d656-45c6-a931-9db0ddb53cd2">

**Comment by EbenSorkin** [comment]
I think we can close this

**Comment by vv-monsalve** [comment]
Outlines have been revised and adjusted. Closing this issue here.
