### ISSUE TITLE
Update Great Vibes - Final Steps

### ISSUE THREAD

**Issue by RobLeuschke** [googlefonts/great-vibes#21]
Modifications have been made per our meeting (Friday Sept.8, 2023).
Notations have been placed in the glyphs that have been modified. See the font file's glyph cells to see those annotations.
Please review the following modifications and send comments if further adjustments need to be made.

- [x] The lowercase "o" has been redesigned to distinguish from the "a." 
- [x] Inferior and superior numbers have been modified and kerned.
- [x] Dot accents and other diacritics have been modified.
- [x] The weight of the Fhook has been modified.
- [x] The weight of the "b" has been modified.
- [x] Some forms have been changed from ss01 to init (r) or fina (t) features.
- [x] The weights of the eturn and eopen have been modified.
- [x] The small upsilon has been modified to connect on the left side.
- [x] The rfishhook has been modified to connect on the left side.
- [x] Click glyphs have been italicized. 

<img width="1016" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/38ccfe42-cce5-4c15-87d3-f5a8692905d5">

There may be other minor adjustments to glyphs that have not been annotated.

**Comment by RobLeuschke** [comment]
The strokes on the F I J and T were insconsistent. So, I've modified them The original forms are still in the background layer:
<img width="1197" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/00525d93-46f7-4a63-986e-a5658f3eaa37">

(NOTE: The alternate T and F have also been modified.)

**Comment by vv-monsalve** [comment]
This is looking smoother now. Remember to also improve the intersection between the main stem and the top horizontal strokes (in F, T, and others) ;)

**Comment by RobLeuschke** [comment]
The top crossbars are now fixed.
