### ISSUE TITLE
lambdastroke

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#22]
Lambdastroke glyph still needs to follow the indications given in one previous meeting:

> `lambdastroke` should be constructed as a different letter from Greek lamda. The stroke should be as tall as the ascenders, similar terminal as f)

Also, the orientation of the terminal stroke should go the left.

Reference:
<img width="577" alt="Screen Shot 2023-09-28 at 18 26 35" src="https://github.com/googlefonts/great-vibes/assets/48698976/5d8d0cad-7d1f-4592-9ccf-41e638ec5ca0">

Currently in the font:
<img width="404" alt="Screen Shot 2023-09-28 at 18 21 56" src="https://github.com/googlefonts/great-vibes/assets/48698976/c49e7226-1954-4cc3-9e82-8b5e3bb9f4e6">

**Comment by vv-monsalve** [comment]
Lambdastroke has been modified in v1.016 and is looking more consistent now.
@EbenSorkin, how do you see it?
<img width="846" alt="Screen Shot 2023-10-09 at 16 35 32" src="https://github.com/googlefonts/great-vibes/assets/48698976/9a6da827-f34e-41d9-9fb2-9e3be1d1a091">

**Comment by moyogo** [comment]
This looks good to me.

FYI: U+A7DA LATIN CAPITAL LETTER LAMBDA, U+A7DB LATIN SMALL LETTER LAMBDA, U+A7DC LATIN CAPITAL LETTER LAMBDA WITH STROKE will be added to Unicode next year.

U+A7DB LATIN SMALL LETTER LAMBDA will be the stroke-less form of lambdastroke, and the other two their capitals.

**Comment by vv-monsalve** [comment]
@moyogo Should we add them now, then?

**Comment by moyogo** [comment]
@vv-monsalve for the Latin Beyond set, definitely. Considering Great Vibes already has the /lambdastroke it would make sense here as well.

**Comment by RobLeuschke** [comment]
I've created the Lambda (capital) and the lambda (small). However, the Unicode generated by the GLYPHS app are not the same as mentioned. They are: U+039B and U+03BB respectively.
<img width="923" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/52c5d705-ac34-44c8-8b6e-f5c880481be2">

**Comment by moyogo** [comment]
@RobLeuschke Awesome!

For the Unicode values, the default Glyphs data uses /Lambda/lambda for the Greek letters, so rename the glyphs as uniA7DA for the capital Latin lambda and uniA7DB for the lowercase Latin lambda, and uniA7DC for the capital Latin lambda with stroke. So it should be /uniA7DA/uniA7DB/uniA7DC/lambdastroke for all four.
Unfortunately the names /Lambda-latin/lambda-latin/Lambdastroke won’t work unless we setup a GlyphsData file.

For the uppercase /uniA7DC (Lambdastroke) you can use /uniA7DA (Lambda-latin) as a component and have the stroke at a slightly steeper angle through joint or above it (but that might need some adjustment then).

**Comment by EbenSorkin** [comment]
I'd better modify some sources!

-e.

**Comment by RobLeuschke** [comment]
@moyogo  
I've created the glyphs with the unicode designations per your instructions:
<img width="1020" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/ad1e9c03-89d7-4be9-8a2e-1fc66d34c873">

**Comment by EbenSorkin** [comment]
This is done

**Comment by vv-monsalve** [comment]
Closing this issue here.
