### ISSUE TITLE
`tbar`, `tdiagonalstroke`, `thook` revision

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#24]
@EbenSorkin, what do you think of these letters? Size of strokes, position and special `thook`, should it have the above stroke more related to the letter `f`?

<img width="428" alt="Screen Shot 2023-09-28 at 20 38 54" src="https://github.com/googlefonts/great-vibes/assets/48698976/55e64df4-b693-433a-93db-1898ecf5833b">

Reference font
<img width="329" alt="Screen Shot 2023-09-28 at 20 43 09" src="https://github.com/googlefonts/great-vibes/assets/48698976/0f9f6661-6d35-4c86-a55e-89062f7aab2c">

**Comment by EbenSorkin** [comment]
The height of the hook in thook needs to be taller like f but I think it
needs to retain this hook shape and not match the stylized f

**Comment by vv-monsalve** [comment]
- [x] `tdiagonalstroke` needs to have the same height as standard t (could be done with component)
- [x] `thook` ascender needs to be taller

<img width="834" alt="Screen Shot 2023-10-09 at 16 43 07" src="https://github.com/googlefonts/great-vibes/assets/48698976/09a02404-0fa1-462a-8c7e-d58800e76fd3">

**Comment by RobLeuschke** [comment]
@vv-monsalve 

<img width="550" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/138527fe-ad56-489a-8db5-99cd69e30e95">

I've made the adjustments and this issue can be closed if you would like.

**Comment by EbenSorkin** [comment]
I made tdiagonalstroke use a component 
t hook checks out as fixed.

**Comment by vv-monsalve** [comment]
Ty, Eben. After the latest revision to bars and strokes I'm closing this issue here.
