### ISSUE TITLE
upsilon-latin review

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#25]
@EbenSorkin What do you think about `upsilon-latin` thickness and connections?

Currently in font

<img width="715" alt="Screen Shot 2023-09-28 at 21 15 27" src="https://github.com/googlefonts/great-vibes/assets/48698976/1b38cf9c-c04b-4140-b022-a9e5a076c2b3">

Reference fonts

<img width="368" alt="Screen Shot 2023-09-28 at 21 16 31" src="https://github.com/googlefonts/great-vibes/assets/48698976/b0fa53a0-2738-4db8-bb2f-8a6cd36b0949">
<img width="395" alt="Screen Shot 2023-09-28 at 21 16 53" src="https://github.com/googlefonts/great-vibes/assets/48698976/21a0644c-b09b-42fd-859d-ec59ac153ed5">

**Comment by EbenSorkin** [comment]
This seems a bit problematic not in gesture but in contrast. It seems like
the left downstroke side should be heavier that the right upstroke side
like the o.

**Comment by RobLeuschke** [comment]
Here are better connections for the upsilon:
<img width="777" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/9c6f5690-2dcc-49ad-8a48-cb7868b0b639">

**Comment by RobLeuschke** [comment]
I have modified the cedillacomb. It looked "off" to me. So, here is the revision (on the left) from the original (on the right).
<img width="378" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/83d7dc01-ff68-4fd2-a2c2-4ddc916ef942">

**Comment by vv-monsalve** [comment]
Rob will work on:
- The `upsilon` connection at the same time as those of `o` and `oopen`.
- Cedilla's contrast fine-tuning

**Comment by EbenSorkin** [comment]
The revised one looks great. I wonder how it looks with the letters it goes with.

**Comment by RobLeuschke** [comment]
As I said, ALL connectors have been modified. Here are a few examples of how things are working. The o, upsilon, oopen, and schwa. (oʊorɔorə)

<img width="1577" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/e2f27cd6-2664-4fb2-8e06-6abd290be801">

**Comment by EbenSorkin** [comment]
The extension inside the open o seems to be potentially confusing. Let’s
try it with the interior line less long

**Comment by RobLeuschke** [comment]
@EbenSorkin 
Do you mean more like this (on the right)?
<img width="836" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/b039467b-1871-42e7-b8f2-6fa1342fa9c4">

**Comment by EbenSorkin** [comment]
No I mean that it normally looks like a c with the openness of it being
important to its identity. I know that in this style the c curls into
itself. But I think when it is turned it looks like schwa or turned e (ǝ,
ə).

**Comment by EbenSorkin** [comment]
Something more like
[image: image.png]

Because if you set a text that uses a ton of these ( and at least one
language does ) the little noise inside with a swash is going to be a
problem I think.

I'll send you a sample text to set next so you can see what I mean

-e.

**Comment by EbenSorkin** [comment]
Try this text

Bambara

O yɔrɔ bɛɛ, mobile bɛ lakoori dugumɔgɔw fɛ, bangebaw. Ni si tômô na, u'b'a
fara bôla ka to a kolo ye barsa a kolo de na fa ka bon. Ɲɔnin taamasiɲɛ
fɔlɔw ye farigan, nunjibɔ, ɲɛ bilennen don ani a bɛ dimi, ani sɔgɔsɔgɔ.
Togodala musow bɛ nakɔbaara kɛ kosɛbɛ walasa k.’u ka tile musakaw sɔrɔ. A
baara fɔlɔ de ye ka mɔgɔw lafaamu munna delinako ninnu dabilali nafa ka
bon. U hakɛ tata bɛɛ ka kan ka ta don o don. Sɛrɛkili don, min bɛ kamarili
kɛ arɔndisimen nataw la: Sikorolen, Kangari, Gelenlenkɔrɔ, Yɔrɔbugula ani
Kalanna. Ɔrimɔni fana bɛ bangenugu dawolo namaya kosɛbɛ, min bɛ lawaji bali
ka don bangenugu kɔnɔ. A b’a To kuma tɔ bɛ Seereya ka cyɛnlandiya ka
Barika. Zɔnye ka di fali ye kosɛbɛ. Yɔrɔw bɛɛ ni a jɛgɛ tɔgɔ don nka u bɛɛ
bɛ wele ko “sosojɛgɛ”. Sɔgɔsɔgɔninjɛ bɛ muso minnu na, kanjabana, bɛ se ka
olu denw minɛ, sɔgɔsɔgɔninjɛ bɛ min senkɔrɔ. Yen, a donna fanga ka fɔlikulu
min tɔgɔ Bamakɔ Super Rail Band. Kanjabana sɔgɔsɔgɔninjɛ bɛ kɔkɔ dɔɔni
dɔɔni tile dama dɔw walima dɔgɔkun dama dɔw kɔnɔ. O kuma kɛra cɛ dɔ ɲɛna
min tun ye weeleweeleda in mɛ, ka misitigi ka telefɔni nimoro ta. Woro
ɲuguɲugulen man ca yan. Woron son san o san walisa ji ko ka nôgôya cogomi.
N’i y’a lajɛ, situlu bɛ kɛ fɛn o fɛn ye du kɔnɔ, o bɛɛ ye waribɔ musaka ye.
O sɔgɔsɔgɔninjɛ ye kannasɔgɔsɔgɔnijɛ, kɔnɔbaralasɔgɔsɔgɔnijɛ (aw ye ja lajɛ
gafe ɲɛ Bana minnu bɔlen don olu danfaraw dɔnni gɛlɛyaw), wolola
sɔgɔsɔgɔnijɛ, ani kolotugudasɔgɔsɔgɔnijɛ (i n’a fɔ kunbere).
Worokɔrɔgɛnɛgɛnɛw mana nɛ ta, ka kɛnɛya ka tila funu tuguni. Wikipeja ye
dɔnnisoba dɔ ye Ɛntɛrinɛti sira fɛ diɲɛ dɔnnin caman ɲɛfɔlen bɛ min kan.
Sigi Dô tun bè ka maden dugu môgôw ni siri ka da u kun n'o ye Do ye. Walima
u bɛ se ka ɲɛsiw bin ɲɛ kɔnɔ, ka joli bila ɲɛjɛ la, min bɛ laban fiyentɔya
ma. U bɛ banamisɛnni caman furakɛ, i n’a fɔ: wololabanaw, kololabanaw,
furulabanaw walima ɲɛgɛnɛkɛsiralabanaw (ɲɛgɛnɛbarani). Tɔnɔgɔ dɔw bɛ don
joli la ka ɲɛgɛnɛbilenni bila mɔgɔ la. Tinminɛmuso walima kɛnɛya tigilamɔgɔ
minnu bɛ musow lajigin, jolilajɔfura caman ka kan ka sɔrɔ olu bolokɔrɔ.
Sɔgɔma, daraka fɛgɛman dunnen kɔfɛ, aw bɛ nikulozamidi ta. N’i mago bɛ ka
dɔnnin min ɲɛɲini, i b’o sɛbɛn a kɔnɔ, k’o ɲininkali k’a la.
Sinkɔrɔkɛrɛdimi bɛ mɔgɔ minɛ ninakilidegunbana dɔw senfɛ walima u kɔfɛ, i
n’a fɔ ɲɔni, keteketeni, murasɔgɔsɔgɔ, disidimi, sisan, walima banajugu
wɛrɛ minnu bɛ mɔgɔ laada, kɛrɛnkɛrɛnnenya la denfitiniw ni mɔgɔkɔrɔbaw.
Silamɛya tarikudɔnna, Al-Sa’df b’a kɔnɔta fɔ ak’a donni kan Tumutu : «Soni
Ali donna Tumutu, a ye tɲɔni belebelew kɛ, ka dugu jeni ka flenkloci, ka
mɔgɔw caman nimatɔrɔ. Pɔsɔnni bɛ fɛn o fɛn na. San 1943, a ye kunnafoni
sɛbɛ sintin "Kenedugu ɲɛ"(l'oeil de Kénédougou) min bɛ marabaa lagoshi. San
2004, Ture kɛra Ɲafunke mɛri ye. O ɲɔ min bɛ filen kɔnɔ, o de bɛ taa kɛ ka
nafɛnw, sukaro walima tulu san. Ɔwɔ, an bɛ se ka gɛlɛya damadɔ fɔ baara in
na bi. Nka, fura kɛrɛnkɛrɛnnen tɛ yen ko bana dɔ tɛ se ka furakɛ min kɔ. Ni
nônôkènè bila,a bè sunôgo ka kè nônô kumu ye. Nin fura ye
silifametɔkizazɔli ni sumayafura faralen ɲɔgɔn kan (sulfaméthoxazole avec
triméthoprime), dɔw b’a wɛlɛ ko TMP-SMX. Ni a yɔrɔ bɛ aw ŋɛɲɛ, a bɛ aw
jenijeni walima a ji bɛ bɔ, aw bɛ a saniya, aw bɛ finimugu dɔ su jisuma na,
ka o da a la. Ni aw sɔmina sumayabana na walima farigan taa ka segin na, ni
a ka nɔgɔ aw ma, aw bɛ taa jolisɛgɛsɛgɛ kɛ dɔgɔtɔrɔso la. Ni aw bɛ sigida
la, sumayabana jolisɛgɛsɛgɛ tɛ kɛ yɔrɔ min, farigan gɛlɛn fɛn o fɛn mana
tɛmɛ aw dɔnyɔrɔ kan, aw bɛ olu furakɛ i n’a fɔ sumayabana. Kɔnɔtiɲɛ fɛɛrɛ
minnu bɛna ni basibɔn juguman ye, bana walima saya yɛrɛ, olu de ye: ka
kalani walima ka fɛn kologɛlɛnman wɛrɛw don denso kɔnɔ, ka den diyagoya
labɔ, ka tubabufuraw ta walima farafinfuraw. Kɔnɔtiɲɛ bɛ muso caman sɔrɔ u
ka ɲɛnɛmaya kɔnɔ k’a sɔrɔ u m’a jateminɛkɛ’o don.

Lowercase Letters:
a n i ɔ ɛ k l u m b o e g s r d w f t y j ɲ ô c è h z é p ɛ x v ŋ

Capital Letters:
S N T K W O A B Y Ɲ U Ɔ D P M G Z R Ɛ X

Word count: 682
Character count: 3761

**Comment by RobLeuschke** [comment]
@EbenSorkin 
I think you meant to post an image [image: image.png], but it doesn't preview.

**Comment by EbenSorkin** [comment]
I have emailed you both directly instead with the image

**Comment by RobLeuschke** [comment]
After looking at the text you gave (thank you, btw), I am seeing what you mean, and I am also seeing issues with the 'eopen.'

<img width="1221" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/2a3b4bc0-1168-4fa0-8ced-6e608401847b">
Is this "oopen" better?

**Comment by EbenSorkin** [comment]
Yeah that's working better. :-) To what extent might it make sense to make
the o open one that doesn't join at all?

**Comment by RobLeuschke** [comment]
@EbenSorkin 
Do you mean something more like this (this is now 'oopen.ss01')?
<img width="286" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/dfa836e2-37e6-4c08-8a7a-2952b06c6b38">

**Comment by EbenSorkin** [comment]
Yeah! 😁

**Comment by RobLeuschke** [comment]
OK, I will make this the base, and keep it with the connecting version as ss01.

**Comment by moyogo** [comment]
The open o should be much more open still.

The way it’s often drawn nowadays connects below, maybe like л, and doesn’t go up much before going half-circle the other way, there can be a connection with the next letter after raising the pen:
<img width="286" alt="rɔr" src="https://github.com/googlefonts/great-vibes/assets/1923747/349bc664-d185-410f-8869-d1cb770164d2">


The form connecting on top first is older but less obvious as it may be confused with s. But it also is more open and there’s often a loop to go into the connection with the next letter. The loop can be closed like the loops on r, w, etc.
<img width="531" alt="Screenshot 2023-10-14 at 12 59 25" src="https://github.com/googlefonts/great-vibes/assets/1923747/243a4486-0d91-4c7a-a95d-4444b1729a01">

**Comment by moyogo** [comment]
I guess connecting the open o with the following letter like the o could work as well.

For the upsilon, it’s often confusable with the vhook ʋ but no language orthography uses both, only IPA transcriptions (which are out of scope) do. So they should be distinct but it’s OK if they are similar.

As a side note: Historically upsilon-latin (ʊ) was a small capital u (ᴜ) for a vowel and vhook (ʋ) was a round v for a consonant. However some languages use vhook (ʋ) as a vowel, likely because it had practically the same shape on some typewriter fonts used to make material or in some handwritten forms.

What’s the current shape of ʊ, ʋ and v ?

**Comment by RobLeuschke** [comment]
Here are the current  v, ʊ, and ʋ .
<img width="494" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/739c7e2b-d15e-4daf-8e3b-7a62d8427083">

**Comment by RobLeuschke** [comment]
@moyogo 
I've created an SS02 version (on the right here). It connects on both sides. I'm unsure if the right connector.  Is it preferred or is it even necessary?

<img width="1150" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/045cc267-0be6-48bd-b2a4-903b9be4aace">

**Comment by RobLeuschke** [comment]
As per discussion on 10/20/23, I've adjusted the weight of the upsilon.
OLD:
<img width="509" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/93a64891-a882-41bd-9aae-8ea6caba798e">

NEW:
<img width="496" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/fc6b42a3-e7bb-4b15-9c6d-6ba768f9020e">

**Comment by RobLeuschke** [comment]
I've created a non-connecting 'eturned' and made the original (which still connects) an alternate ss01. In addition, I gave them a very subtle added weight on the right.

<img width="887" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/1390b9ac-b6ae-4cda-b1c0-71a6071b4999">

**Comment by EbenSorkin** [comment]
These seem to be fixed. I created an o without an outstroke to precede some letters and made some CAlt OT features to go with it.
<img width="233" alt="image" src="https://github.com/googlefonts/great-vibes/assets/2181213/072be88a-1d1a-4456-8a63-77c1f60fe3de">

**Comment by vv-monsalve** [comment]
Upsilon Uc and Lc plus others, have been revised and adjusted.
