### ISSUE TITLE
Bars and strokes review

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#26]
Many different components are used to produce the bar in the `bar` or `stroke` glyphs; therefore, they are not consistent in style, weight, length, etc.

Please review them and
- [x] Create or adjust different width `stroke` components (e.g. `strokeshortcomb` `strokemedcomb`) to ensure consistency among them.
- [x] Ensure combining either only outlines or components in the composite glyphs, but not mixing them.

<img width="1751" alt="Screen Shot 2023-09-28 at 21 50 38" src="https://github.com/googlefonts/great-vibes/assets/48698976/6ddce3e1-984b-4647-a3ff-8be4015805f0">
<img width="352" alt="Screen Shot 2023-09-28 at 21 54 45" src="https://github.com/googlefonts/great-vibes/assets/48698976/2d75a098-44dd-4c15-af6b-a22fbcd166cc">

**Comment by vv-monsalve** [comment]
Eben did an extensive revision to the bars. So please, rather than modifying those changes, please take them and normalize them in `strokeshortcomb` `strokemedcomb` `strokelongcomb` wherever possible. Unifying further their style (the terminal stroke endings, thickness etc) E.g. `Hbar`.

**Comment by RobLeuschke** [comment]
I have done the best I could to standardize all of the stroked characters (as well as those with a bar). I created several stroke components for those glyphs that require such strokes. I replaced the glyphs that used hyphens or endash components with these new components:
strokemedcomb strokevertcomb strokevertlongcomb strokelongcomb

The lambda stroke has been modified. 

<img width="1822" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/5c4c95d7-46b6-40d5-b463-2d31b7863b5d">

**Comment by vv-monsalve** [comment]
Seeing the image, the bar in `Hbar` still needs to be consistent :)

**Comment by RobLeuschke** [comment]
Yes, I was afraid to touch it based on Eben's comments. I would prefer it
to have the same long stroke, but that would be quite different from the
crossbar in the base glyph.

Not sure what to do about it, so I've made an sso1 version and we can talk
about it:
[image: image.png]

R

**Comment by vv-monsalve** [comment]
Eben said:

> Hbar - the top bar is meant to take more attention than the lower one in this letter, so I made it wider. This could be tweaked further for a more nuanced effect.

As long as you keep the length, you could use the long-stroke shape. This would visually relate it to the other bars in the font making it clear it is an added bar, different from the structural bar in the H.

**Comment by RobLeuschke** [comment]
I made an alternate to compare. The one on the right is Hbar.ss01:

![image](https://github.com/googlefonts/great-vibes/assets/57553693/7f5b7a73-6f11-4272-96ca-7d7813ce6795)

**Comment by vv-monsalve** [comment]
No need to create a `.ss01` shape. You can make the latter the main version and keep the original one in the background.
cc @EbenSorkin

**Comment by RobLeuschke** [comment]
Very good.... thanks

**Comment by EbenSorkin** [comment]
These have all been adjusted to use non-scaled components

**Comment by EbenSorkin** [comment]
This looks done

**Comment by vv-monsalve** [comment]
Closing this after the latest overall revision
