### ISSUE TITLE
`Rtail` and `dtail`

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#27]
@EbenSorkin should these letters use something similar as an extension of the main stem instead of this short tail?

**Currently in the source file**
<img width="205" alt="Screen Shot 2023-09-29 at 22 04 39" src="https://github.com/googlefonts/great-vibes/assets/48698976/898935e2-9396-489c-adeb-4ac711ecac24">
<img width="150" alt="Screen Shot 2023-09-29 at 20 45 19" src="https://github.com/googlefonts/great-vibes/assets/48698976/4523bb36-a127-4313-b43d-52a91fbc79c4">

Reference fonts
<img width="194" alt="Screen Shot 2023-09-29 at 20 36 17" src="https://github.com/googlefonts/great-vibes/assets/48698976/1f52de86-0b75-4937-b44e-e06631c7e590">
<img width="198" alt="Screen Shot 2023-09-29 at 20 36 27" src="https://github.com/googlefonts/great-vibes/assets/48698976/fbd43511-322c-4951-9326-9b27580612c9">
<img width="182" alt="Screen Shot 2023-09-29 at 20 45 37" src="https://github.com/googlefonts/great-vibes/assets/48698976/71f99870-878e-4d71-8f5d-1edd47bc8d68">
<img width="179" alt="Screen Shot 2023-09-29 at 20 45 50" src="https://github.com/googlefonts/great-vibes/assets/48698976/7413427a-d83c-4200-89e4-790a5c4965a6">

**Comment by vv-monsalve** [comment]
@RobLeuschke, I can confirm, after revision with Eben, that this needs to be changed to make the "tails" more of an extension of the main stem, as seen in the reference fonts.

**Comment by RobLeuschke** [comment]
Here is what I have come up with. 
<img width="957" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/ebd773da-4a8f-41e8-a2a5-96073cbdf9a6">

**Comment by vv-monsalve** [comment]
@EbenSorkin, these are the new `tail` letters in the file. However I wonder if the tail stroke should be more related to the lower part on `J`

<img width="1154" alt="Screen Shot 2023-10-09 at 18 20 39" src="https://github.com/googlefonts/great-vibes/assets/48698976/75caaa53-61c8-4df9-b559-1aed782d8566">
<img width="725" alt="Screen Shot 2023-10-09 at 18 20 21" src="https://github.com/googlefonts/great-vibes/assets/48698976/6aaaea6b-3edd-4f10-9edf-be75ed2a25a3">

**Comment by vv-monsalve** [comment]
@RobLeuschke `rtail` still needs to receive the `j` stroke
<img width="524" alt="Screen Shot 2023-10-09 at 18 29 38" src="https://github.com/googlefonts/great-vibes/assets/48698976/9b37bd6e-0531-4c8c-b24e-07ea44b77a9b">

**Comment by RobLeuschke** [comment]
Snell Roundhand's rtail is like this:
<img width="84" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/3b7ad56d-b526-412e-8e0f-b6481a4943e7">
Based on the look of other fonts (eg. Snell Roundhand and others), I think it may be better to have some consistency with regard to the dtail and qhooktail. So, here is what I came up with (ss01 versions). If you think these new forms work better, I can swap them out with the present forms.
<img width="1505" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/45b3d6d2-1d34-46df-b87f-4c3f5a4ceb8e">

**Comment by EbenSorkin** [comment]
The new forms draw attention to their identity really well. I would like to
set them in hook using languages and see how they look in words and
sentences

**Comment by moyogo** [comment]
Dafrican (Ɖ, capital of ɖ) never has this form (except in this one book https://twitter.com/moyogo/status/635174860931657730), it always has the same shape as Eth/Dstroke. I’d use Eth/Dstroke as a composite.
The Dafrican doesn’t need to have an alternate with the hook below at this point.

The tail can be more pronounced but don’t have to be as long as they are clearly distinct from regular descenders. Normal descenders are straight so either form (original or ss01) work.
Maybe the kink in the ss01 forms needs to be ironed out.
A paragraph set in both would help.

@EbenSorkin should I provide samples here?

**Comment by moyogo** [comment]
@RobLeuschke 
For Rtail the tail can be more pronounced as well and extend more to the right.

**Comment by RobLeuschke** [comment]
@moyogo 
Deni, is this what you mean (emulating the Qhook)?
<img width="811" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/07ad1815-f725-4c74-8954-6ca7d142a274">

**Comment by EbenSorkin** [comment]
Dtail and Dtail fixed

**Comment by EbenSorkin** [comment]
q and rtail fixed

**Comment by EbenSorkin** [comment]
Rtail is fixed

**Comment by moyogo** [comment]
@RobLeuschke yes, that looks good except for /Dafrican/dtail. The lowercase had a tail hook but the uppercase is typically identical to /Dcroat/Eth.

**Comment by vv-monsalve** [comment]
Dafrican is fixed.
