### ISSUE TITLE
 Л (El-cy) and М (Em-cy), Љ (Lje-cy), Ԉ (Komilje-cy)

### ISSUE THREAD

**Issue by vikagrabowska** [googlefonts/great-vibes#42]
I would like to propose some changes to the contrast and shape of El-cy leg. 

Original drawing
<img width="638" alt="Pasted Graphic 30" src="https://github.com/googlefonts/great-vibes/assets/78556166/10513bf8-a00a-4313-ab36-239dcad1bbcb">

Proposal. Usually the left leg of Л is thin and starting to gain weight closer to its bottom part. 
<img width="709" alt="Pasted Graphic 29" src="https://github.com/googlefonts/great-vibes/assets/78556166/8edda183-03c0-4225-84df-453fba492850">

The change would affect also М which uses similar curve as Л in Great Vibes, and the Љ and Ԉ.

In Љ and Ԉ the left part should be an identical to Л letterform. Or it’s slightly narrower version since both of these letterforms are wide. This is a similar case as narrowing Latin m in comparison to n or narrowing Æ in comparison to A and E.

**Comment by moyogo** [comment]
Ԉ and other letters of the Molodstov Komi alphabet haven't been used since 1940.
