### ISSUE TITLE
Ф (Ef-cy)

### ISSUE THREAD

**Issue by vikagrabowska** [googlefonts/great-vibes#44]
While Ef-cy.ss01 is looking pretty great, I’m wondering if Ef-cy (default version) can use a swash at the top of the stem to add more charm to the shape? It can perhaps be the same swash as in Ef-cy.ss01. Or here are some more possible ideas.
<img width="99" alt="Pasted Graphic 3" src="https://github.com/googlefonts/great-vibes/assets/78556166/ff927172-dc68-4cd3-a3d5-29672bbbb89e">

<img width="83" alt="Pasted Graphic 4" src="https://github.com/googlefonts/great-vibes/assets/78556166/f873496d-2d86-4ac2-b8f5-af91691258de">

**Comment by RobLeuschke** [comment]
Something like this?
<img width="730" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/90436235-5b9c-4519-9285-d7643a94e811">

**Comment by vikagrabowska** [comment]
Hi Rob, 
Yes, it looks good :)
