### ISSUE TITLE
Please create a `b.init`

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#45]
After the change to the initial stroke of the letter `b`, a `b.init` would be needed

<img width="964" alt="Screen Shot 2023-10-09 at 16 47 09" src="https://github.com/googlefonts/great-vibes/assets/48698976/09f8a769-a5c2-4b4e-a8a8-88cdab4bb7a6">

**Comment by RobLeuschke** [comment]
I have created init forms for all of the characters that have a slight connecting 'bump' in the stem. The top line shows the base characters, and the bottom shows the init forms.
<img width="1286" alt="image" src="https://github.com/googlefonts/great-vibes/assets/57553693/70d49e1e-d645-45c4-999a-457c31660151">

**Comment by EbenSorkin** [comment]
Looks done!

**Comment by vv-monsalve** [comment]
Agree. After our last revisions this could be considered done.
