### ISSUE TITLE
many ss01 and ss02 and init and fina letters need diacritic versionsor open type features will be English only!

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/great-vibes#62]
Working on adding this now.

**Comment by EbenSorkin** [comment]
Related issue - Some letters with diacritics will not be needed because they don't occur at the ends of works or the start. Filtering these out will save file size slightly.

**Comment by moyogo** [comment]
@EbenSorkin which ones?

**Comment by EbenSorkin** [comment]
Nearly all the variants. (init fina ss01 etc.)

I have almost completed the update to address this problem.

-e.

**Comment by EbenSorkin** [comment]
This was fixed
