### ISSUE TITLE
Browser diff 

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/great-vibes#7]
Hi @crystaltype. This is a new Browser Image after solving the[ shifted up glyphs](https://github.com/googlefonts/great-vibes/issues/6) issue.

Please check/solve now the following

- [x] During that process the marks were misplaced. Please review this plus [diffenator report](https://github.com/googlefonts/great-vibes/issues/8), and ensure all the diacritics are ok, particularly stacked ones. 
- [x] Uppercase `tilde` is misplaced and smaller than the published font
- [ ] Some letters such as `b`, `d` and `z` among others need to go back to the previous non-looped shapes into the main version, and the looped ones should be a stylistic set.

**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/120964348-d0c32000-c728-11eb-8719-9341683b67f9.gif)

**Comment by vv-monsalve** [comment]
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/120966132-6c559000-c72b-11eb-9d7a-762e048f3ff1.gif)

**Comment by crystaltype** [comment]
@vv-monsalve Hello Viviana,
I inspected the file and I saw the basic lowercase letters actually don't have swashes. I'm not sure why they're replaced with the swash ones in browser preview. Do you know what could be the reason? Maybe the stylistic set is enabled by default?

I've solved the 2 other mentioned issues. And I also changed z back. Please check the newest file in my fork if needed.
<img width="782" alt="Screen Shot 2021-06-08 at 05 36 00" src="https://user-images.githubusercontent.com/20129845/121096149-cfbeeb00-c81b-11eb-9dc6-650532936026.png">

<img width="848" alt="Screen Shot 2021-06-08 at 05 36 39" src="https://user-images.githubusercontent.com/20129845/121095987-8373ab00-c81b-11eb-9888-7dba00e8c0af.png">

**Comment by vv-monsalve** [comment]
@crystaltype after pulling latest files at commit 94f1759236a93390b84890ce257f1308e4c96015 there are still misplaced diacritics

I'm solving it now. Please don't make any changes in the source file.

![Screen Shot 2021-06-09 at 18 33 22](https://user-images.githubusercontent.com/48698976/121442468-5e815400-c951-11eb-825a-1c65418019fd.png)
![Screen Shot 2021-06-09 at 18 31 25](https://user-images.githubusercontent.com/48698976/121442487-64773500-c951-11eb-8169-d2519b4c7be5.png)
![Screen Shot 2021-06-09 at 18 40 36](https://user-images.githubusercontent.com/48698976/121442966-3d6d3300-c952-11eb-8446-160cec4c6c43.png)

**Comment by vv-monsalve** [comment]
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/121465080-c26c4280-c97a-11eb-8db2-d40e9ced99be.gif)
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/121465085-c4ce9c80-c97a-11eb-847d-ea01a7d85602.gif)
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/121465089-c5673300-c97a-11eb-88dc-2847fc86d4e4.gif)
